---
- hosts: all
  tasks:
    - shell: pkill mongo
      with_items:
        - mongos
        - mongoc
        - mongod-mongo1
        - mongod-mongo2
        - mongod-mongo3
      ignore_errors: yes
    - file: path=/data/db state=absent

