---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.

- hosts: all
  roles:
  - role: common

- hosts: mongo_servers_shard1_replication
  roles:
  - role: mongod_servers

- hosts: mongo_servers_shard2_replication
  roles:
  - role: mongod_servers

- hosts: mongoc_servers
  roles:
  - role: mongoc

- hosts: mongos_servers
  roles:
  - role: mongos_servers
# run shading test
#- include: shard_test.yml


